### ISSUE TITLE
cannot find the recastdemo.exe after build the serverrecast successfully

### ISSUE THREAD

**Issue by husha1993** [darkwere/ServerRecast#1]
![recastdemo](https://user-images.githubusercontent.com/21278701/41307476-22cfc60c-6e2e-11e8-802d-2a1cf5631f5d.png)

Hi,
Thanks for releasing this great work!
I have built this plugin successfully with vs2017 and ue4.18. And the "Serverrecast" button appear in the top pannel of ue editor when I open my project. While when I press the "Serverrecast" button, it says "cannot find the recastdemo.exe" as showed in the above screen shot.

**Comment by darkwere** [comment]
You missed p.4 of instruction. You must build RecastDemo. Follow the instructions of recastnavigation project.

**Comment by husha1993** [comment]
@darkwere 
I see, thanks. After building the recastdemo, I can press the  "Serverrecast" button.

I follow the instructions 9, RecastDemo program shows up but without my level in it.
![serverrecast](https://user-images.githubusercontent.com/21278701/41317611-93626c96-6e4a-11e8-9590-85d6d7d307ce.png)

**Comment by darkwere** [comment]
Choose TileMesh sample first.

**Comment by husha1993** [comment]
@darkwere 
I choose TileMesh sample first, while my level is still absent from the recastdemo program:
![recastviews](https://user-images.githubusercontent.com/21278701/41378152-050846f4-6f13-11e8-9cc3-b168947c6ffd.png)

I open the RecastNavMesh-Default.obj file in blender, it can show something as below:
![blenderviews](https://user-images.githubusercontent.com/21278701/41378131-f2c23be4-6f12-11e8-84d9-3cb4b22b64b1.png)

The level displayed in ue4  level editor:
![cityviews](https://user-images.githubusercontent.com/21278701/41378189-25fedddc-6f13-11e8-8543-29cb2a5e69f7.png)

**Comment by husha1993** [comment]
@darkwere 
What I want to do is to obtain all the positions (i.e., x, y, z) of points that has no collision with buildings, trees, etc, in the level.
I thought I can obtain such positions from recastnavmesh, so I export the recastnavmesh from ue4 and tried to read such data.
Do you know if it is possible to read the positions of points within the green regions(as showed in screen shot 3 above) from recastnavmehs or is there any other method to obtain the positions of points that have no collision with other actors in the level during level design process?
Thanks.

**Comment by darkwere** [comment]
You should check the docs of recastnavigation project. This question is out of scope related to this plugin.

**Comment by husha1993** [comment]
Sure.. Thank you!
