### ISSUE TITLE
Can't see anything in recastnavigation when click ServerRecast

### ISSUE THREAD

**Issue by powers0010** [darkwere/ServerRecast#2]
follow the steps, all look like right, but when click ServerRecast, and recastnavigation was open, i can't see anything in recastnavigation.

**Comment by darkwere** [comment]
Did you select the type of sample mesh?
Did you pressed the Build button?

**Comment by powers0010** [comment]
![111](https://user-images.githubusercontent.com/31006865/42273979-a7b9180a-7fbd-11e8-929f-3f55535f59e9.png)
Yes,like this,but when I press the Build button, it was crashed!

**Comment by darkwere** [comment]
Could you send me your UE project? I wanna take a look!

**Comment by powers0010** [comment]
My Engine Version is 4.19.2, I just create a empty program。
Otherwise, uints of UE4 is centimeter,and uints of KBE is meter, Should I scale when used in serve?

**Comment by darkwere** [comment]
Don't scale it! Make a normal landscape in UE!
The plugin will scale it for you in RecastNavigation!

**Comment by powes0010** [comment]
HI, I send my plugin resource to you, I just create a new program and put them in it.

**Comment by VectorL1990** [comment]
I have the same problem(blank in recastnavigation) and I did not scale it at all

**Comment by VectorL1990** [comment]
the most wired thing is that it worked well serveral months ago, but it doesn't work right now, my version now is ue4.19.1

**Comment by darkwere** [comment]
The current version of ServerRecast is compatible to UE4.18 only. I'm working on compatibility with the newer versions of UE.
